=== maximejimenez/UMLChangeAnalyzer/ARCA_Schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="ARCA_CONFIG">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EA-EXPORT" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="EXCLUDE-CASE-SENSITIVITY" maxOccurs="unbounded" minOccurs="0"/>
							<xs:element name="EXCLUDE-PACKAGES" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="PACKAGE-NAME" maxOccurs="unbounded" minOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EXCLUDED-ELEMENTS" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="ELEMENT-NOTE"/>
										<xs:element type="xs:string" name="ELEMENT-TYPE"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EXCLUDED-ATTRIBUTES" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="ATTRIBUTE-NOTE"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EXCLUDED-CONNECTORS" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="CONNECTOR-TYPE"/>
										<xs:element type="xs:string" name="CONNECTOR-NOTE"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EXCLUDE-TAGGED-VALUES" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="TAGGED-VALUE-NAME" maxOccurs="unbounded" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ROLES" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ROLE" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="NAME"/>
										<xs:element type="xs:string" name="PACKAGE" maxOccurs="unbounded" minOccurs="1"/>
									</xs:sequence>
									<xs:attribute type="xs:string" name="Model" use="optional"/>
									<xs:attribute type="xs:string" name="UTMonly" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element type="xs:string" name="RESULTS_PATH"/>
				<xs:element name="FEATURES" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:date" name="START_DATE"/>
							<xs:element type="xs:date" name="END_DATE"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
		        <xs:element name="EXTRACT_MULTIPLE">
		          <xs:complexType>
		            <xs:sequence>
		              <xs:element maxOccurs="unbounded" name="RELEASE">
		                <xs:complexType>
		                  <xs:simpleContent>
		                    <xs:extension base="xs:string">
		                      <xs:attribute name="VERSION" type="xs:string" use="required" />
		                    </xs:extension>
		                  </xs:simpleContent>
		                </xs:complexType>
		              </xs:element>
		            </xs:sequence>
		            <xs:attribute name="EXTRACT_PATH" type="xs:string" use="required" />
		          </xs:complexType>
		        </xs:element>
				<xs:element name="REPORT_CHANGES" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="RELEASE" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
						<xs:attribute type="xs:string" name="REPORT_PATH" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="REPORT_METRICS" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="RELEASE" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
						<xs:attribute type="xs:string" name="REPORT_PATH" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="REPORT_FEATURES" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="SVN"/>
							<xs:element name="FEATURE" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="Name" use="required"/>
											<xs:attribute type="xs:byte" name="Priority" use="required"/>
											<xs:attribute type="xs:byte" name="Policy" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="REPORT_PATH" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== maximejimenez/UMLChangeAnalyzer/UML_Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<ARCA_CONFIG xmlns="C:\Users\USERNAME\Desktop\UMLResults\Config\" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="C:\Users\USERNAME\Desktop\UMLResults\Config\ ARCA_Schema.xsd">
	<EA-EXPORT>
		<EXCLUDE-CASE-SENSITIVITY>true</EXCLUDE-CASE-SENSITIVITY>
		<EXCLUDE-PACKAGES>
			<PACKAGE-NAME>NonRelevantPackage.mo</PACKAGE-NAME>
		</EXCLUDE-PACKAGES>
		<EXCLUDED-ELEMENTS>
			<ELEMENT-NOTE>true</ELEMENT-NOTE>
			<ELEMENT-TYPE>Note</ELEMENT-TYPE>
		</EXCLUDED-ELEMENTS>
		<EXCLUDED-ATTRIBUTES>
			<ATTRIBUTE-NOTE>true</ATTRIBUTE-NOTE>
		</EXCLUDED-ATTRIBUTES>
		<EXCLUDED-CONNECTORS>
			<CONNECTOR-TYPE>NoteLink</CONNECTOR-TYPE>
			<CONNECTOR-NOTE>true</CONNECTOR-NOTE>
		</EXCLUDED-CONNECTORS>
	</EA-EXPORT>
	<ROLES>
		<ROLE Model="M1">
			<NAME>Metamodel</NAME>
			<PACKAGE>Absyn.mo</PACKAGE>
		</ROLE>
	</ROLES>
	<RESULTS_PATH>C:\Users\USERNAME\Desktop\UMLResults\Results</RESULTS_PATH>
	<REPORT_CHANGES REPORT_PATH="C:\Users\USERNAME\Desktop\UMLResults\Results">
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.1.1</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.1.2</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.2</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.3</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.4</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.4.1</RELEASE>
	</REPORT_CHANGES>
	<REPORT_METRICS REPORT_PATH="C:\Users\USERNAME\Desktop\UMLResults\Results">
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.1.1</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.1.2</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.2</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.3</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.4</RELEASE>
		<RELEASE>C:\Users\USERNAME\Desktop\UMLResults\XML\2.4.1</RELEASE>		
	</REPORT_METRICS>
</ARCA_CONFIG>
